#!/bin/bash
# jsonファイルから読み上げテキストを作成するスクリプト
# usage:./json2list [json file] [save filename]

set -e
# コマンドパーサ
CMDNAME=`basename $0`
if [ $# -lt 2 ]; then
  echo "Usage: ${CMDNAME} [json file] [save filename]" 1>&2
  exit 1
fi

aim=`cat $1|jq -r .aim`
member=`cat $1|jq -r .member[]|sed 's/$/さん、/g'`
member_number=`cat $1 |jq -r .member | jq length`
agenda=`cat $1|jq -r .agenda[].title`
agenda_items=`cat $1|jq .agenda |jq length`
prework=`cat $1|jq -r .prework`

echo "start01 この会議の参加者は${member}です。"|tr -d "\n" > $2
echo "" >> $2
echo "start02 この会議の目的は${aim}です。" >> $2
echo "start03 アジェンダは" >> $2

for((i=0;i<${agenda_items};i++)); do
  if [ $((i+1)) = ${agenda_items} ]; then
    echo "start0$((i+4)) `echo $agenda|cut -d " " -f $((i+1))`です。" >> $2
  else
    echo "start0$((i+4)) `echo $agenda|cut -d " " -f $((i+1))`" >> $2
  fi
done

for((i=0;i<${agenda_items};i++)); do
  speaker=`cat $1|jq -r .agenda[$i].speaker`
  if [ $speaker == "all" ]; then
    speaker="皆"
  fi
  title=`cat $1|jq -r .agenda[$i].title`
  class=`cat $1|jq -r .agenda[$i].class`
  echo "agenda0$i ${speaker}さん。「${title}」の${class}をお願いします。" >> $2
  echo "summary0$i ${speaker}さん。結論をまとめてください。" >> $2
  echo "stop0$i ${class}が終わりましたら「OK」と言ってください。" >> $2
done

member=`cat $1|jq -r .member[$(($RANDOM % $member_number))]`
echo "assign01 最後に${member}さん、次回までのトゥードゥーをまとめてください。" >> $2
