#!/bin/bash
# ファイル名と書き起こしが書かれたファイルから
# tts音声を作成するスクリプト。
# list fileの書き方:[filename] [text]
#                   [filename] [text]
#                             :
#                             : 
# usage:./list2text [list file] [save dir]
# Author:Inoue

# コマンドパーサ
CMDNAME=`basename $0`
if [ $# -lt 2 ]; then
  echo "Usage: ${CMDNAME} [list file] [save dir]" 1>&2
  exit 1
fi

cat $1|while read line
do
  save_tts $2 $line
done
