#!/bin/bash
# アジェンダの分類に合わせて音楽再生、残り時間まで読み上げるスクリプト
# usage:./play_bgm [project name] [agenda number] [part a or b] [tts dir] [volume]
# Author:Inoue


# コマンドパーサ
CMDNAME=`basename $0`
if [ $# -lt 5 ] || \
   [ `echo $1 | grep "\."` ] || \
   [ ! -e ./json/$1.json ]; then
  echo "Usage: ${CMDNAME} " [project name] [agenda number] [part a or b] [tts dir] 1>&2
  exit 1
fi

project=$1
agenda_num=$2
part=$3
tts_dir=$4
vol=$5


# 分類（class）に合わせてBGMを選択
json=`cat ./json/${project}.json`
class=`echo $json|jq -r .agenda[${agenda_num}].class`
case ${class} in
  "報告" ) bgm=tell.mp3 ;;
  "討議" ) bgm=brest.mp3 ;;
  "承認" ) bgm=morning.mp3 ;;
esac


# 該当アジェンダの割当時間に合わせて、読み上げ残り時間を変更
time=$((`echo $json|jq -r .agenda[${agenda_num}].time` * 60))
if [ $time -lt 600 ]; then # 予定時間が10分より短かったら
  alarm=180 # 3分前にお知らせ
  alarm_tts=time02.wav
else # 予定時間が10分より長かったら
  alarm=300 # 5分前にお知らせ
  alarm_tts=time01.wav
fi


# ランダムな開始位置から音楽を再生
duration=`soxi -D bgm/${bgm}`
if [ ${part} == "a" ]; then
  play ./bgm/${bgm} trim 0 $((time-alarm)) gain -n ${vol}
  play ./bgm/SE/bell1.mp3
  play ${tts_dir}/${alarm_tts}
else
  play ./bgm/${bgm} trim 0 $((alarm-60)) gain -n ${vol}
  play ./bgm/SE/bell2.mp3
  play ${tts_dir}/time03.wav
fi
