#!/bin/bash
# Sound of Textのapiを使って、google ttsを保存スクリプト
# Author:Inoue

set -e
# コマンドパーサ
CMDNAME=`basename $0`
if [ $# -lt 3 ] || [ `echo $2 | grep "\."` ]; then
	echo "Usage: ${CMDNAME} [save dir] [filename (Not required suffix)] [text]" 1>&2
  exit 1
fi
save_dir=$1
filename=$2
shift
shift
text=$*

# tmpのjsonファイル
json_tmp=$(mktemp)
echo '{"'engine'":"'Google'","'data'":{"'text'":"'$text'","'voice'":"'ja-JP'"}}' > ${json_tmp}
cat ${json_tmp}

# jsonをPOSTしてTTS音声idを取得
POST_URL=https://api.soundoftext.com/sounds
result=`curl ${POST_URL} -H 'Content-Type:application/json' -d @${json_tmp}`
id=`echo ${result} | jq -r .id`

# POSTで得たidでmp3のURLを生成
GET_URL=https://api.soundoftext.com/sounds/${id}
result=`curl ${GET_URL}`
mp3_URL=`echo ${result} | jq -r .location`
while [ ${mp3_URL} = "null" ]
  do
    result=`curl ${GET_URL}`
    mp3_URL=`echo ${result} | jq -r .location`
  done

# mp3をダウンロードして保存
mp3_tmp=$(mktemp --suffix=.mp3)
wget -O ${save_dir}/${filename}.mp3 ${mp3_URL}

# 一時ファイル削除
rm ${json_tmp}
